[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00E5FF"
backgroundColor = "#0B1326"
secondaryBackgroundColor = "#1E293B"
textColor = "#DAE2FD"
font = "sans serif"